site_url : https://github.com/asalvadorc/BBDD_POSTGRES_DCL
site_name: BD - Bases de Dades
theme: 
  name: readthedocs
  logo: assets/logocaminas.png

extra_css:
  - css/extra.css
  - img/favicon.ico 

markdown_extensions:
  - admonition
  - tables    
  - attr_list
  - toc 
  - pymdownx.emoji
  - pymdownx.extra
  - pymdownx.superfences

nav:
  - POSTGRESQL - DCL :
    - 0. Introducción: 1_introducci.md
    #- 1. DCL: 1-DCL.md
    - 1. DCL: 1-DCLv2.md 
    - 1.1 Práctica: 1.1-Practica.md
    - 2. TCL: 2-TCL.md
    - 2.1 Práctica: 2.1-Practica.md

    
  
    
